// =============================================================================
//  DADOS MOCKADOS — usados quando o Supabase ainda não está configurado.
//  Permite visualizar o site 100% sem backend. Quando as variáveis do
//  Supabase existirem, as páginas passam a buscar no banco (ver lib/carrinho.ts).
//
//  Os dados refletem o catálogo real da Agro Mundo Animal (Tabuleiro/Floripa):
//  rações, petiscos, medicamentos veterinários, pesca, ferramentas e agro.
// =============================================================================

import type {
  Categoria,
  Produto,
  Unidade,
  ZonaEntrega,
} from "@/types/database.types";

const img = (seed: string) =>
  `https://placehold.co/600x600/0F3D91/F7F9FC?text=${encodeURIComponent(
    seed,
  )}&font=manrope`;

// Fotos reais baixadas do Instagram da loja (@agromundoanimaltabuleiro)
const fotoReal = (nome: string) => `/produtos-reais/${nome}`;

export const mockCategorias: Categoria[] = [
  {
    id: "cat-racoes",
    nome: "Rações",
    slug: "racoes",
    icone: "Wheat",
    ordem: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-petiscos",
    nome: "Petiscos",
    slug: "petiscos",
    icone: "Bone",
    ordem: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-medicamentos",
    nome: "Medicamentos Veterinários",
    slug: "medicamentos",
    icone: "Pill",
    ordem: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-pesca",
    nome: "Pesca",
    slug: "pesca",
    icone: "Fish",
    ordem: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-ferramentas",
    nome: "Ferramentas",
    slug: "ferramentas",
    icone: "Hammer",
    ordem: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-ferragens",
    nome: "Ferragens",
    slug: "ferragens",
    icone: "Wrench",
    ordem: 6,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-agro",
    nome: "Agro & Insumos",
    slug: "agro",
    icone: "Sprout",
    ordem: 7,
    created_at: new Date().toISOString(),
  },
];

export const mockProdutos: Produto[] = [
  // --- Rações ----------------------------------------------------------------
  {
    id: "p-racao-cachorro-15",
    categoria_id: "cat-racoes",
    nome: "Ração Premier Formula Cães Adultos 15kg",
    slug: "racao-premier-formula-caes-adultos-15kg",
    descricao:
      "Alimento completo e balanceado para cães adultos de porte médio. Sabor carne e cereais. Embalagem reforçada de 15kg.",
    preco_cents: 18990,
    preco_promocional_cents: 16990,
    preco_por_kg: true,
    peso_kg: 15,
    estoque: 24,
    estoque_minimo: 5,
    qtd_minima: 1,
    multiplo: 1,
    unidade_medida: "cx",
    foto_url: fotoReal("ig_00.jpg"),
    destaque: true,
    ativo: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p-racao-gato-7",
    categoria_id: "cat-racoes",
    nome: "Ração Whiskas Sabor Peixe 7,5kg",
    slug: "racao-whiskas-sabor-peixe-7-5kg",
    descricao:
      "Nutrição completa para gatos adultos. Ricamente saborosa com peixes selecionados.",
    preco_cents: 12490,
    preco_promocional_cents: null,
    preco_por_kg: true,
    peso_kg: 7.5,
    estoque: 12,
    estoque_minimo: 4,
    qtd_minima: 1,
    multiplo: 1,
    unidade_medida: "cx",
    foto_url: fotoReal("ig_06.jpg"),
    destaque: true,
    ativo: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p-racao-frango-25",
    categoria_id: "cat-racoes",
    nome: "Ração Polet Inicial Frangos 25kg",
    slug: "racao-polet-inicial-frangos-25kg",
    descricao:
      "Para frangos de corte na fase inicial (1 a 21 dias). Alta proteína para crescimento acelerado.",
    preco_cents: 8990,
    preco_promocional_cents: null,
    preco_por_kg: true,
    peso_kg: 25,
    estoque: 40,
    estoque_minimo: 8,
    qtd_minima: 1,
    multiplo: 1,
    unidade_medida: "cx",
    foto_url: fotoReal("ig_08.jpg"),
    destaque: false,
    ativo: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p-racao-boi-25",
    categoria_id: "cat-racoes",
    nome: "Sal Mineral Boi Forte 25kg",
    slug: "sal-mineral-boi-forte-25kg",
    descricao:
      "Sal mineralizado para bovinos de corte e leite. Suplementação completa de macro e microminerais.",
    preco_cents: 7990,
    preco_promocional_cents: 7490,
    preco_por_kg: true,
    peso_kg: 25,
    estoque: 60,
    estoque_minimo: 10,
    qtd_minima: 1,
    multiplo: 1,
    unidade_medida: "cx",
    foto_url: fotoReal("ig_09.jpg"),
    destaque: false,
    ativo: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // --- Petiscos -------------------------------------------------------------
  {
    id: "p-petisco-bifinho",
    categoria_id: "cat-petiscos",
    nome: "Bifinho Snack Cães 500g",
    slug: "bifinho-snack-caes-500g",
    descricao:
      "Petisco macio e saboroso para cães. Ideal como recompensa no adestramento.",
    preco_cents: 1890,
    preco_promocional_cents: null,
    preco_por_kg: false,
    peso_kg: 0.5,
    estoque: 30,
    estoque_minimo: 6,
    qtd_minima: 1,
    multiplo: 1,
    unidade_medida: "pct",
    foto_url: fotoReal("ig_11.jpg"),
    destaque: true,
    ativo: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // --- Medicamentos ---------------------------------------------------------
  {
    id: "p-vermifugo-caes",
    categoria_id: "cat-medicamentos",
    nome: "Vermífugo Drontal Plus Cães 4 comprimidos",
    slug: "vermifugo-drontal-plus-caes-4cp",
    descricao:
      "Anti-helmíntico de amplo espectro para cães. Combate vermes em uma dose única.",
    preco_cents: 4290,
    preco_promocional_cents: null,
    preco_por_kg: false,
    peso_kg: null,
    estoque: 18,
    estoque_minimo: 5,
    qtd_minima: 1,
    multiplo: 1,
    unidade_medida: "cx",
    foto_url: fotoReal("ig_03.jpg"),
    destaque: true,
    ativo: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p-antipulga",
    categoria_id: "cat-medicamentos",
    nome: "Antipulgas Frontline Cães até 10kg",
    slug: "antipulgas-frontline-caes-ate-10kg",
    descricao:
      "Antipulgas e carrapaticida tópico. Proteção por até 30 dias com 1 aplicação.",
    preco_cents: 5990,
    preco_promocional_cents: 5490,
    preco_por_kg: false,
    peso_kg: null,
    estoque: 3,
    estoque_minimo: 5,
    qtd_minima: 1,
    multiplo: 1,
    unidade_medida: "un",
    foto_url: fotoReal("ig_05.jpg"),
    destaque: false,
    ativo: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // --- Pesca ----------------------------------------------------------------
  {
    id: "p-vara-pesca",
    categoria_id: "cat-pesca",
    nome: "Vara de Pesca Telescópica 3,60m",
    slug: "vara-de-pesca-telescopica-3-60m",
    descricao:
      "Vara de fibra de vidro, leve e resistente. Ideal para pesca esportiva em rios e mar.",
    preco_cents: 6490,
    preco_promocional_cents: null,
    preco_por_kg: false,
    peso_kg: null,
    estoque: 15,
    estoque_minimo: 4,
    qtd_minima: 1,
    multiplo: 1,
    unidade_medida: "un",
    foto_url: fotoReal("ig_10.jpg"),
    destaque: true,
    ativo: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p-kit-anzois",
    categoria_id: "cat-pesca",
    nome: "Kit Anzóis Variados 50 peças",
    slug: "kit-anzois-variados-50pecas",
    descricao:
      "Sortimento de anzóis de aço para diferentes tipos de pesca. Vem em organizador.",
    preco_cents: 2490,
    preco_promocional_cents: null,
    preco_por_kg: false,
    peso_kg: null,
    estoque: 25,
    estoque_minimo: 5,
    qtd_minima: 1,
    multiplo: 1,
    unidade_medida: "cx",
    foto_url: fotoReal("ig_07.jpg"),
    destaque: false,
    ativo: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // --- Ferramentas ----------------------------------------------------------
  {
    id: "p-enxada",
    categoria_id: "cat-ferramentas",
    nome: "Enxada Aço Corte 6 polegadas",
    slug: "enxada-aco-corte-6-polegadas",
    descricao:
      "Enxada com lâmina de aço temperado e cabo de madeira reflorestada. Robusta para roçada pesada.",
    preco_cents: 4990,
    preco_promocional_cents: null,
    preco_por_kg: false,
    peso_kg: 1.8,
    estoque: 20,
    estoque_minimo: 5,
    qtd_minima: 1,
    multiplo: 1,
    unidade_medida: "un",
    foto_url: fotoReal("ig_04.jpg"),
    destaque: true,
    ativo: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p-tesoura-poda",
    categoria_id: "cat-ferramentas",
    nome: "Tesoura de Poda Bypass Manual",
    slug: "tesoura-de-poda-bypass-manual",
    descricao:
      "Tesoura com lâmina de aço teflon e cabo ergonômico. Corte limpo em galhos até 2cm.",
    preco_cents: 3490,
    preco_promocional_cents: 2990,
    preco_por_kg: false,
    peso_kg: 0.3,
    estoque: 14,
    estoque_minimo: 4,
    qtd_minima: 1,
    multiplo: 1,
    unidade_medida: "un",
    foto_url: fotoReal("ig_01.jpg"),
    destaque: false,
    ativo: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // --- Agro -----------------------------------------------------------------
  {
    id: "p-semente-milho",
    categoria_id: "cat-agro",
    nome: "Semente de Milho Híbrido 20.000 sementes",
    slug: "semente-de-milho-hibrido-20000-sementes",
    descricao:
      "Milho híbrido de alta produtividade. Resistente a pragas comuns da região sul.",
    preco_cents: 28990,
    preco_promocional_cents: null,
    preco_por_kg: false,
    peso_kg: 8,
    estoque: 9,
    estoque_minimo: 3,
    qtd_minima: 1,
    multiplo: 1,
    unidade_medida: "pct",
    foto_url: fotoReal("ig_02.jpg"),
    destaque: true,
    ativo: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p-defensivo",
    categoria_id: "cat-agro",
    nome: "Herbicida Glifosato Concentrado 1 Litro",
    slug: "herbicida-glifosato-concentrado-1-litro",
    descricao:
      "Herbicida sistêmico de ação total. Uso agrícola — siga as instruções do rótulo.",
    preco_cents: 4590,
    preco_promocional_cents: null,
    preco_por_kg: false,
    peso_kg: 1,
    estoque: 22,
    estoque_minimo: 6,
    qtd_minima: 1,
    multiplo: 1,
    unidade_medida: "lt",
    foto_url: fotoReal("ig_07.jpg"),
    destaque: false,
    ativo: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // --- Ferragens ------------------------------------------------------------
  {
    id: "p-prego",
    categoria_id: "cat-ferragens",
    nome: "Prego 17/21 Aço Galvanizado 1kg",
    slug: "prego-17-21-aco-galvanizado-1kg",
    descricao:
      "Prego de aço galvanizado a fogo, medida 17/21 (2,4mm x 54mm). Vendido por quilo.",
    preco_cents: 1890,
    preco_promocional_cents: null,
    preco_por_kg: true,
    peso_kg: 1,
    estoque: 80,
    estoque_minimo: 15,
    qtd_minima: 1,
    multiplo: 1,
    unidade_medida: "kg",
    foto_url: fotoReal("ig_04.jpg"),
    destaque: true,
    ativo: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p-arame-farpado",
    categoria_id: "cat-ferragens",
    nome: "Arame Farpado 500m Rolo",
    slug: "arame-farpado-500m-rolo",
    descricao:
      "Arame farpado galvanizado para cerca de divisas e currais. Rolo com 500 metros.",
    preco_cents: 12990,
    preco_promocional_cents: 11990,
    preco_por_kg: false,
    peso_kg: 22,
    estoque: 12,
    estoque_minimo: 3,
    qtd_minima: 1,
    multiplo: 1,
    unidade_medida: "un",
    foto_url: fotoReal("ig_08.jpg"),
    destaque: false,
    ativo: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p-cadeado",
    categoria_id: "cat-ferragens",
    nome: "Cadeado de Latão 50mm com 2 Chaves",
    slug: "cadeado-latão-50mm-2-chaves",
    descricao:
      "Cadeado robusto de latão maciço, resistente à ferrugem. Ideal para portões e depósitos.",
    preco_cents: 2990,
    preco_promocional_cents: null,
    preco_por_kg: false,
    peso_kg: 0.3,
    estoque: 35,
    estoque_minimo: 8,
    qtd_minima: 1,
    multiplo: 1,
    unidade_medida: "un",
    foto_url: fotoReal("ig_09.jpg"),
    destaque: false,
    ativo: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockUnidades: (Unidade & {
  zonas: ZonaEntrega[];
})[] = [
  {
    id: "uni-tabuleiro",
    nome: "Agro Mundo Animal — Tabuleiro (Matriz)",
    slug: "tabuleiro",
    endereco: "Rua 600, nº 555, Sala 01 — Tabuleiro dos Oliveiras, Itapema/SC · CEP 88220-000",
    whatsapp: "5547999895365",
    ativa: true,
    created_at: new Date().toISOString(),
    zonas: [
      {
        id: "z-tab-retirada",
        unidade_id: "uni-tabuleiro",
        nome: "Retirada na loja (Tabuleiro)",
        tipo: "retirada",
        valor: "retirada",
        frete_percentual: 0,
        prazo_horas: 1,
        ativa: true,
        created_at: new Date().toISOString(),
      },
      {
        id: "z-tab-bairro",
        unidade_id: "uni-tabuleiro",
        nome: "Tabuleiro dos Oliveiras e bairros próximos",
        tipo: "bairro",
        valor: "tabuleiro dos oliveiras",
        frete_percentual: 3,
        prazo_horas: 24,
        ativa: true,
        created_at: new Date().toISOString(),
      },
      {
        id: "z-tab-itapema",
        unidade_id: "uni-tabuleiro",
        nome: "Itapema (demais bairros)",
        tipo: "cidade",
        valor: "itapema",
        frete_percentual: 3,
        prazo_horas: 24,
        ativa: true,
        created_at: new Date().toISOString(),
      },
      {
        id: "z-tab-balneario",
        unidade_id: "uni-tabuleiro",
        nome: "Balneário Camboriú / Camboriú",
        tipo: "cidade",
        valor: "balneário camboriú",
        frete_percentual: 5,
        prazo_horas: 48,
        ativa: true,
        created_at: new Date().toISOString(),
      },
      {
        id: "z-tab-porto",
        unidade_id: "uni-tabuleiro",
        nome: "Porto Belo / Itajaí / Navegantes",
        tipo: "cidade",
        valor: "itajaí",
        frete_percentual: 5,
        prazo_horas: 48,
        ativa: true,
        created_at: new Date().toISOString(),
      },
      {
        id: "z-tab-blumenau",
        unidade_id: "uni-tabuleiro",
        nome: "Blumenau / Brusque (Vale do Itajaí)",
        tipo: "cidade",
        valor: "blumenau",
        frete_percentual: 10,
        prazo_horas: 72,
        ativa: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "uni-centro",
    nome: "Agro Mundo Animal — Centro",
    slug: "centro",
    endereco: "Centro, Itapema/SC",
    whatsapp: "5547999895365",
    ativa: true,
    created_at: new Date().toISOString(),
    zonas: [
      {
        id: "z-cent-retirada",
        unidade_id: "uni-centro",
        nome: "Retirada na loja (Centro)",
        tipo: "retirada",
        valor: "retirada",
        frete_percentual: 0,
        prazo_horas: 1,
        ativa: true,
        created_at: new Date().toISOString(),
      },
      {
        id: "z-cent-centro",
        unidade_id: "uni-centro",
        nome: "Centro de Itapema",
        tipo: "bairro",
        valor: "centro",
        frete_percentual: 3,
        prazo_horas: 24,
        ativa: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
];
