// =============================================================================
//  DADOS MOCKADOS — TEMPLATE UNIVERSAL DE DEMONSTRAÇÃO.
//  Usados quando Supabase não está configurado.
//
//  Estes produtos/categorias/unidades são EXEMPLOS genéricos para o cliente
//  visualizar como o site fica. Ao contratar, substituímos pelos produtos
//  reais (via painel admin ou importação).
// =============================================================================

import type {
  Categoria,
  Produto,
  Unidade,
  ZonaEntrega,
} from "@/types/database.types";

const img = (seed: string, cor = "1A9D63") =>
  `https://placehold.co/600x600/${cor}/F1F8F4?text=${encodeURIComponent(seed)}&font=manrope`;

const agora = new Date().toISOString();

export const mockCategorias: Categoria[] = [
  {
    id: "cat-1",
    nome: "Categoria 1",
    slug: "categoria-1",
    icone: "Package",
    ordem: 1,
    created_at: agora,
  },
  {
    id: "cat-2",
    nome: "Categoria 2",
    slug: "categoria-2",
    icone: "Package",
    ordem: 2,
    created_at: agora,
  },
  {
    id: "cat-3",
    nome: "Categoria 3",
    slug: "categoria-3",
    icone: "Package",
    ordem: 3,
    created_at: agora,
  },
  {
    id: "cat-4",
    nome: "Categoria 4",
    slug: "categoria-4",
    icone: "Package",
    ordem: 4,
    created_at: agora,
  },
  {
    id: "cat-5",
    nome: "Categoria 5",
    slug: "categoria-5",
    icone: "Package",
    ordem: 5,
    created_at: agora,
  },
];

export const mockProdutos: Produto[] = [
  {
    id: "p-1",
    categoria_id: "cat-1",
    nome: "Produto em Destaque 1",
    slug: "produto-destaque-1",
    descricao:
      "Descrição do produto de demonstração. Ao contratar, este texto será substituído pela descrição real do seu produto.",
    preco_cents: 19990,
    preco_promocional_cents: 16990,
    preco_por_kg: false,
    peso_kg: null,
    unidade_medida: "un",
    estoque: 24,
    estoque_minimo: 5,
    qtd_minima: 1,
    multiplo: 1,
    foto_url: img("Produto 1", "F59E0B"),
    destaque: true,
    ativo: true,
    created_at: agora,
    updated_at: agora,
  },
  {
    id: "p-2",
    categoria_id: "cat-1",
    nome: "Produto em Destaque 2",
    slug: "produto-destaque-2",
    descricao:
      "Outro produto de demonstração para mostrar como fica o catálogo com fotos e preços.",
    preco_cents: 12490,
    preco_promocional_cents: null,
    preco_por_kg: false,
    peso_kg: null,
    unidade_medida: "un",
    estoque: 12,
    estoque_minimo: 4,
    qtd_minima: 1,
    multiplo: 1,
    foto_url: img("Produto 2", "1A9D63"),
    destaque: true,
    ativo: true,
    created_at: agora,
    updated_at: agora,
  },
  {
    id: "p-3",
    categoria_id: "cat-2",
    nome: "Produto com Preço por Kg",
    slug: "produto-preco-por-kg",
    descricao:
      "Demonstração de produto vendido por peso. O sistema calcula o preço por kg automaticamente.",
    preco_cents: 8990,
    preco_promocional_cents: null,
    preco_por_kg: true,
    peso_kg: 3,
    unidade_medida: "cx",
    estoque: 18,
    estoque_minimo: 4,
    qtd_minima: 1,
    multiplo: 1,
    foto_url: img("Produto por Kg", "14563B"),
    destaque: true,
    ativo: true,
    created_at: agora,
    updated_at: agora,
  },
  {
    id: "p-4",
    categoria_id: "cat-2",
    nome: "Produto em Promoção",
    slug: "produto-promocao",
    descricao:
      "Demonstração de produto com preço promocional (riscado + preço novo).",
    preco_cents: 11990,
    preco_promocional_cents: 6990,
    preco_por_kg: false,
    peso_kg: null,
    unidade_medida: "un",
    estoque: 10,
    estoque_minimo: 3,
    qtd_minima: 1,
    multiplo: 1,
    foto_url: img("Promoção", "DC2626"),
    destaque: true,
    ativo: true,
    created_at: agora,
    updated_at: agora,
  },
  {
    id: "p-5",
    categoria_id: "cat-3",
    nome: "Produto com Estoque Baixo",
    slug: "produto-estoque-baixo",
    descricao:
      "Demonstração de produto com estoque baixo — aparece o badge 'Últimas unidades'.",
    preco_cents: 4290,
    preco_promocional_cents: null,
    preco_por_kg: false,
    peso_kg: null,
    unidade_medida: "un",
    estoque: 3,
    estoque_minimo: 5,
    qtd_minima: 1,
    multiplo: 1,
    foto_url: img("Estoque Baixo", "0EA5E9"),
    destaque: true,
    ativo: true,
    created_at: agora,
    updated_at: agora,
  },
  {
    id: "p-6",
    categoria_id: "cat-3",
    nome: "Produto Esgotado",
    slug: "produto-esgotado",
    descricao:
      "Demonstração de produto sem estoque — aparece o badge 'Esgotado'.",
    preco_cents: 2490,
    preco_promocional_cents: null,
    preco_por_kg: false,
    peso_kg: null,
    unidade_medida: "un",
    estoque: 0,
    estoque_minimo: 6,
    qtd_minima: 1,
    multiplo: 1,
    foto_url: img("Esgotado", "64748B"),
    destaque: false,
    ativo: true,
    created_at: agora,
    updated_at: agora,
  },
  {
    id: "p-7",
    categoria_id: "cat-4",
    nome: "Produto com Venda por Múltiplo",
    slug: "produto-multiplo",
    descricao:
      "Demonstração de produto vendido em múltiplos de 6 unidades (ex: caixas fechadas).",
    preco_cents: 3490,
    preco_promocional_cents: null,
    preco_por_kg: false,
    peso_kg: null,
    unidade_medida: "cx",
    estoque: 30,
    estoque_minimo: 8,
    qtd_minima: 6,
    multiplo: 6,
    foto_url: img("Múltiplo 6", "1A9D63"),
    destaque: false,
    ativo: true,
    created_at: agora,
    updated_at: agora,
  },
  {
    id: "p-8",
    categoria_id: "cat-5",
    nome: "Produto Simples",
    slug: "produto-simples",
    descricao:
      "Produto de demonstração padrão, sem promoção nem regras especiais.",
    preco_cents: 2990,
    preco_promocional_cents: null,
    preco_por_kg: false,
    peso_kg: null,
    unidade_medida: "un",
    estoque: 50,
    estoque_minimo: 10,
    qtd_minima: 1,
    multiplo: 1,
    foto_url: img("Produto Simples", "14563B"),
    destaque: false,
    ativo: true,
    created_at: agora,
    updated_at: agora,
  },
];

export const mockUnidades: (Unidade & { zonas: ZonaEntrega[] })[] = [
  {
    id: "uni-1",
    nome: "Sua Empresa — Loja 1 (Matriz)",
    slug: "loja-1",
    endereco: "Seu endereço aqui — Sua Cidade/UF · CEP 00000-000",
    whatsapp: "5500000000000",
    ativa: true,
    created_at: agora,
    zonas: [
      {
        id: "z1",
        unidade_id: "uni-1",
        nome: "Retirada na loja (Matriz)",
        tipo: "retirada",
        valor: "retirada",
        frete_percentual: 0,
        prazo_horas: 1,
        ativa: true,
        created_at: agora,
      },
      {
        id: "z2",
        unidade_id: "uni-1",
        nome: "Bairro da matriz",
        tipo: "bairro",
        valor: "bairro exemplo",
        frete_percentual: 5,
        prazo_horas: 24,
        ativa: true,
        created_at: agora,
      },
      {
        id: "z3",
        unidade_id: "uni-1",
        nome: "Cidade da matriz",
        tipo: "cidade",
        valor: "cidade exemplo",
        frete_percentual: 7,
        prazo_horas: 48,
        ativa: true,
        created_at: agora,
      },
    ],
  },
  {
    id: "uni-2",
    nome: "Sua Empresa — Loja 2 (Filial)",
    slug: "loja-2",
    endereco: "Seu endereço aqui — Sua Cidade/UF",
    whatsapp: "5500000000000",
    ativa: true,
    created_at: agora,
    zonas: [
      {
        id: "z4",
        unidade_id: "uni-2",
        nome: "Retirada na loja (Filial)",
        tipo: "retirada",
        valor: "retirada",
        frete_percentual: 0,
        prazo_horas: 1,
        ativa: true,
        created_at: agora,
      },
    ],
  },
];
